default_inputs:
    clean_workdir: False
    kpoints_distance: 0.15
    kpoints_force_parity: False
    max_iterations: 5
    meta_parameters:
        conv_thr_per_atom: 0.2e-9
        etot_conv_thr_per_atom: 1.e-5
    pseudo_family: 'SSSP/1.3/PBEsol/efficiency'
    pw:
        metadata:
            options:
                max_wallclock_seconds: 43200  # Twelve hours
                withmpi: True
        parameters:
            CONTROL:
                calculation: scf
                forc_conv_thr: 1.e-4
                tprnfor: True
                tstress: True
            SYSTEM:
                nosym: False
                occupations: smearing
                smearing: cold
                degauss: 0.02
            ELECTRONS:
                electron_maxstep: 80
                mixing_beta: 0.4
default_protocol: balanced
protocols:
    balanced:
        description: 'Protocol to perform the computation at normal precision at moderate computational cost.'
    stringent:
        description: 'Protocol to perform the computation at high precision at higher computational cost.'
        kpoints_distance: 0.10
        meta_parameters:
            conv_thr_per_atom: 0.1e-9
            etot_conv_thr_per_atom: 0.5e-5
        pseudo_family: 'SSSP/1.3/PBEsol/precision'
        pw:
            parameters:
                CONTROL:
                    forc_conv_thr: 0.5e-4
                SYSTEM:
                    degauss: 0.0125
    fast:
        description: 'Protocol to perform the computation at low precision at minimal computational cost for testing purposes.'
        kpoints_distance: 0.30
        meta_parameters:
            conv_thr_per_atom: 0.4e-9
            etot_conv_thr_per_atom: 1.e-4
        pw:
            parameters:
                CONTROL:
                    forc_conv_thr: 1.e-3
                SYSTEM:
                    degauss: 0.0275
    fpmd:
        description: 'Protocol to perform long first-principles MD at low precision at high computational cost.'
        max_iterations: 25 # FPMD will take a long time to finish
        kpoints_distance: 0.60 # low dense mesh since we should be using supercells
        meta_parameters:
            conv_thr_per_atom: 0.4e-9
            etot_conv_thr_per_atom: 1.e-4
        pw:
            parameters:
                CONTROL:
                    calculation: md
                    nstep: 1.e+5
                    dt: 30 # 1.44 femto seconds
                    iprint: 1
                    forc_conv_thr: 1.e-3
                ELECTRONS:
                    mixing_beta: 0.2 # lower mixing factor since we will be extrapolating wavefunctions anyway
                SYSTEM:
                    degauss: 0.0275
                    nosym: True # gives better stability for long runs
                IONS:
                    wfc_extrapolation: 'second_order' # extrapolation when running FPMD
                    pot_extrapolation: 'second_order'
                    ion_temperature: 'svr' # thermostat
                    tempw: 500 
                    nraise: 100
