default_inputs:
    clean_workdir: False
    kpoints_distance: 0.15
    kpoints_force_parity: False
    meta_parameters:
        conv_thr_per_atom: 0.2e-9
        etot_conv_thr_per_atom: 1.e-5
    pseudo_family: 'SSSP/1.2/PBEsol/efficiency'
    pw:
        metadata:
            options:
                resources:
                    num_machines: 1
                max_wallclock_seconds: 43200  # Twelve hours
                withmpi: True
        parameters:
            CONTROL:
                calculation: scf
                forc_conv_thr: 1.e-4
                tprnfor: True
                tstress: True
            SYSTEM:
                nosym: False
                occupations: smearing
                smearing: cold
                degauss: 0.01
            ELECTRONS:
                electron_maxstep: 80
                mixing_beta: 0.4
default_protocol: moderate
protocols:
    moderate:
        description: 'Protocol to perform the computation at normal precision at moderate computational cost.'
    precise:
        description: 'Protocol to perform the computation at high precision at higher computational cost.'
        kpoints_distance: 0.10
        meta_parameters:
            conv_thr_per_atom: 0.1e-9
            etot_conv_thr_per_atom: 0.5e-5
        pseudo_family: 'SSSP/1.2/PBEsol/precision'
        pw:
            parameters:
                CONTROL:
                    forc_conv_thr: 0.5e-4
    fast:
        description: 'Protocol to perform the computation at low precision at minimal computational cost for testing purposes.'
        kpoints_distance: 0.50
        meta_parameters:
            conv_thr_per_atom: 0.4e-9
            etot_conv_thr_per_atom: 1.e-4
        pw:
            parameters:
                CONTROL:
                    forc_conv_thr: 1.e-3
