default_inputs:
    clean_workdir: False
    kpoints_distance: 0.15
    kpoints_force_parity: False
    max_iterations: 5
    xspectra:
        parameters:
            INPUT_XSPECTRA:
                calculation: xanes_dipole
                xonly_plot: False
                xniter: 2000
                xcheck_conv: 10
                xerror: 0.001
            PLOT:
                xgamma: 0.5
                xnepoint: 2000
                xemin: -10
                xemax: 30
                terminator: True
                cut_occ_states: True
            CUT_OCC:
                cut_desmooth: 0.1
        metadata:
            options:
                resources:
                    num_machines: 1
                max_wallclock_seconds: 43200  # Twelve hours
                withmpi: True
default_protocol: balanced
protocols:
    balanced:
        description: 'Protocol to perform an XANES dipole calculation at normal precision at moderate computational cost.'
    stringent:
        description: 'Protocol to perform an XANES dipole calculation at high precision at higher computational cost.'
        kpoints_distance: 0.10
        xspectra:
            parameters:
                INPUT_XSPECTRA:
                    xerror: 0.0001
    fast:
        description: 'Protocol to perform an XANES dipole calculation at low precision at minimal computational cost for testing purposes.'
        kpoints_distance: 0.50
        xspectra:
            parameters:
                INPUT_XSPECTRA:
                    xerror: 0.01
    replot:
        description: 'Protocol to perform a re-plot of a previous XANES dipole calculation with a low level of broadening (Note: requires the `parent_folder` of a previous XspectraCalculation to work).'
        xspectra:
            parameters:
                INPUT_XSPECTRA:
                    xonly_plot: True
                PLOT:
                    xgamma: 0.3
