version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
    install:
        - method: pip
          path: .
          extra_requirements:
            - docs

# Let the build fail if there are any warnings
sphinx:
    builder: html
    fail_on_warning: true
