dist: trusty
sudo: required

language: python

python:
    - "2.7"
    - "3.6"

cache: pip

services:
    - rabbitmq
    - postgresql
    - docker

addons:
    postgresql: "9.5"
    apt:
        packages:
            - texlive-base
            - texlive-generic-recommended
            - texlive-fonts-recommended
            - texlive-latex-base
            - texlive-latex-recommended
            - texlive-latex-extra
            - dvipng
            - dvidvi

before_install:
    # This is needed for the SSH tests (being able to ssh to localhost)
    # And will also be used for the docker test
    - ssh-keygen -t rsa -N "" -f "${HOME}/.ssh/id_rsa"
    - cp "${HOME}/.ssh/id_rsa.pub" "${HOME}/.ssh/authorized_keys"
    - ssh-keyscan -H localhost >> "${HOME}/.ssh/known_hosts"

    # Build the docker image if needed
    - .ci/before_install.sh

install:
    # Upgrade pip setuptools and wheel to be able to run the next command
    - pip install -U pip==18.1 wheel setuptools reentry

    - pip install "numpy==1.16.4"  # see https://github.com/materialsproject/pymatgen/issues/1520

    # Install the repository with some optional dependencies
    - pip install .[dev,docs]

env:
    - TEST_TYPE="pre-commit"
    - TEST_AIIDA_BACKEND=django TEST_TYPE="docs"
    - TEST_AIIDA_BACKEND=django TEST_TYPE="tests"
    - TEST_AIIDA_BACKEND=sqlalchemy TEST_TYPE="tests"

before_script:
    - .ci/setup_profiles.sh
    - .ci/before_script.sh

script:
    - .ci/test_script.sh

git:
  depth: 3

jobs:
    include:
        - stage: deploy
          if: "tag =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+(a|b|rc)?[0-9]*$"
          services: ignore
          addons: skip
          python: 3.6
          before_install: skip
          install: skip
          before_script: skip
          script: skip
          env: ignore
          before_deploy:
            - echo "We'll deploy $TRAVIS_TAG"
          after_deploy:
            - echo "Deployed $TRAVIS_TAG"
            - echo "Could hook up further triggers here."
          deploy: &pypi
              provider: pypi
              skip_existing: true
              username: aiida-bot
              password:
                  secure: lz5/r+5BndjUEuJsbvMd+4HYb4tdbIiseea8GxmmAu6D7uzch3W40/16npd+/yshtSEMyarpJ2ksW1G99YUPsU29mTwm7y4ODXvU3S4VfJjk3gCuNwagD3hDYv2rMkGGUONIl51NO2PbDKkNqpmUQ/sYZs6D4GFjjiTvc5leXIm+D3s/4MCpNke+90bS/wjJAsFhA1qXZoDndq5oB7rUYwO4na9UlgT3SIRXQaw4vq4RhvqK9eSr63ZNw4naoQU1LkHYPVYlJpANcwkQ6LoQY+IqMNdNb5vlQJTwF74FJgORmAi7UZPqIl7NtPEsECYU10GuLfgTDVsbdE9zKRVQHt8JwsG9udxAO+B7xr5vFGZutibmbZIcmy1IQiOkyhX5L5uGtd+vFCpxHY2iinooTquPGGpexpdqa0pdoBP3ynz0bueLHmG8Quh/3MTr6EyeqB0pxITGlw+tkI0EdMYm1eUxnpEf7lHmx1F1J2l3BIZRiA+F+Dv0zJKKDwb+37/oOFiE//LpEPJ8DavshiwJ+s+pNATAL1YsUOngaoO7U4nyMRHqhBYz3Up9YCC+GDH2wG1loF7QNNXIyGpZ4k3+Rd4sY+DSoXS5TRhtR60a2yGTiQ3LTpbTuCzr592a1BAymbAwTCDMzKiVIhtqgepx6d7VgxRQenrCMwKse973KNI=
              on:
                  repo: aiidateam/aiida-quantumespresso
                  all_branches: true
                  tags: true
