---
profile: test
email: aiida@localhost
first_name: Giuseppe
last_name: Verdi
institution: Khedivial
repository: /tmp/
db_host: 127.0.0.1
db_port: 5432
db_name: postgres
db_username: postgres
db_password: postgres
